# Generated by Django 5.2.1 on 2025-06-01 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
