# Generated by Django 5.2.1 on 2025-06-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_alter_profile_logo_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience_months', models.PositiveIntegerField()),
                ('projects_completed', models.PositiveIntegerField()),
                ('countries', models.PositiveIntegerField()),
            ],
        ),
    ]
