# Generated by Django 5.2.1 on 2025-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='introduction',
            name='name',
            field=models.CharField(default='Muddassir', max_length=100),
        ),
        migrations.AddField(
            model_name='introduction',
            name='role',
            field=models.CharField(default='MERN Stack Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='introduction',
            name='scroll_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='scroll_button_text',
            field=models.CharField(default='See My Work', max_length=100),
        ),
        migrations.AddField(
            model_name='introduction',
            name='short_intro',
            field=models.TextField(default='I turn Figma designs into real web apps using the MERN stack.'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='countries',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='description',
            field=models.TextField(default='I love building Websites!'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='experience_months',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='projects_completed',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
