# Generated by Django 5.2.1 on 2025-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_remove_introduction_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='experience_months',
        ),
        migrations.AddField(
            model_name='introduction',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='name',
            field=models.CharField(default='Muddassir', max_length=15),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='role',
            field=models.CharField(default='MERN Stack Developer', max_length=50),
        ),
    ]
