# Generated by Django 5.2.1 on 2025-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_remove_introduction_experience_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='scroll_button_link',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='scroll_button_text',
        ),
        migrations.AlterField(
            model_name='introduction',
            name='description',
            field=models.TextField(default='I love building Websites!', max_length=50),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='short_intro',
            field=models.TextField(default='I turn Figma designs into real web apps using the MERN stack.', max_length=100),
        ),
    ]
