# Generated by Django 5.2.1 on 2025-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_remove_introduction_scroll_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About', max_length=100)),
                ('title_line_1', models.CharField(default='Every great project begins with', help_text='First line of heading', max_length=100)),
                ('title_line_2', models.CharField(default='a passion for', help_text='Second line with highlighted word', max_length=100)),
                ('title_highlight', models.CharField(default='coding', max_length=30)),
                ('paragraph', models.TextField(help_text='Main about paragraph')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
