# Generated by Django 5.2.1 on 2025-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_aboutsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='paragraph',
            field=models.TextField(help_text='Main about paragraph', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_highlight',
            field=models.CharField(default='coding', max_length=10),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_line_1',
            field=models.CharField(default='Every great project begins with', help_text='First line of heading', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_line_2',
            field=models.CharField(default='a passion for', help_text='Second line with highlighted word', max_length=50),
        ),
    ]
