# Generated by Django 5.2.1 on 2025-07-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_education_experience_delete_resume'),
    ]

    operations = [
    ]
