# Generated by Django 5.2.1 on 2025-07-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0011_auto_20250712_0109'),
    ]

    operations = [
    ]
