# Generated by Django 5.2.1 on 2025-07-11 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0012_auto_20250712_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='company_name',
            field=models.CharField(default='Not specified', help_text="e.g., 'Comsats University Islamabad Abbottabad Campus'", max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, help_text='Select the end date (leave blank if ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_present',
            field=models.BooleanField(default=False, help_text='Check if currently studying here'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select the starting date'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(default='Not specified', help_text="e.g., 'Codematics Inc or GIKI IT Center Islamabad'", max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Select the end date (leave blank if ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_present',
            field=models.BooleanField(default=False, help_text='Check if currently working here'),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select the job start date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(help_text="e.g., 'Bachelor Degree of Software Engineering'", max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text="e.g., 'MERN Stack Developer'", max_length=200),
        ),
    ]
