# Generated by Django 5.2.1 on 2025-07-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0016_remove_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.CharField(default='Not specified', help_text="e.g., 'COMSATS University Islamabad'", max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='01', max_length=2, null=True),
        ),
    ]
