# Generated by Django 5.2.1 on 2025-07-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0019_alter_education_end_year_alter_education_start_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Frontend Development'", max_length=200)),
                ('description', models.TextField(help_text='Describe your specialization briefly.')),
                ('icon', models.CharField(choices=[('las la-bezier-curve', 'Bezier Curve'), ('las la-code', 'Code'), ('las la-database', 'Database'), ('las la-cogs', 'Cogs'), ('las la-stream', 'Stream')], help_text='Icon class (e.g., las la-code)', max_length=50)),
                ('projects', models.PositiveIntegerField(default=0, help_text="How many projects you've completed for this service")),
            ],
        ),
    ]
