# Generated by Django 5.2.1 on 2025-07-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0020_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Describe what this service includes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='projects',
            field=models.PositiveIntegerField(help_text='Number of projects completed for this service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Enter the name of the service (e.g., Frontend Development)', max_length=200),
        ),
    ]
