# Generated by Django 5.2.1 on 2025-07-12 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0021_remove_service_icon_alter_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='skills/')),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Describe what the service includes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='projects',
            field=models.PositiveIntegerField(help_text='Number of completed projects'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='e.g., Frontend Developer', max_length=200),
        ),
    ]
